### ISSUE TITLE
Change Dockerfile to build from source

### ISSUE THREAD

**Issue by mkobit** [mkobit/docker-nifi#1]
The image is currently built by pulling down the developer signing keys, sha1 sum, md5, and verifying it all on the downloaded archive. This works well if the [mirror site](https://www.apache.org/dyn/closer.lua?path=/nifi/0.3.0/nifi-0.3.0-bin.tar.gz) that I picked is close enough to get a faster download, but doesn't work so well when it does not.

It seems like there are 2 options here:
1. Come up with a way to determine the closest mirror
2. Pull from Github and build from source

I think 2 is the easier, and better option.

**Comment by mkobit** [comment]
Still trying to figure out the best way to orchestrate this. 

My initial thoughts were to separate into a "builder" image and an "exec" image, where the builder contains Maven and the requirements to build from source

```
builder image:
  requirements:
    - needs to have:
      a. git
      b. specified maven version from pom.xml
      c. specified java version from pom.xml of NiFi source
      d. gpg keys import of NiFi devs
      e. produces the compressed archive of nifi
    - other considerations:
      a. run tests?
      b. git tag verification (possibly not needed or can't be used with older tags)
      c. git repository caching
      d. .m2 maven dependency caching
    - travis CI considerations:
      a. .m2 mounting from 'host'
      b. .m2 maven dependency caching
      c. git repository caching
      d. persistence/caching across builds

nifi exec image:
  requirements:
    - needs to have:
      a. java (to run nifi)
      b. volumes for repositories (current stuff)
      c. pull from builder image connector (shared volume? read from STDIN?)
    - other considerations
      a. produce an ONBUILD image for consumers?
```

Also, from a Travis CI perspective, caching the dependencies and layers could be a concern if we go from a builder-container which passes the resulting built binary into the executable NiFi container. See https://github.com/travis-ci/travis-ci/issues/5358

**Comment by mkobit** [comment]
Another option would be to separate by responsibility. Possibly connecting/using dependencies with [Docker compose](https://docs.docker.com/compose/compose-file/#depends-on) (this may not help at all if the data cannot be effectively shared in CI service)? 

1. Git container (source provider)
    - Runtime command will have to change for tag verification
2. Build container (`maven` and Java)
    - Build provided source from git container
3. Runtime container (Java)
  - Very cacheable

On a side note about caching :

It might be possible to export the built images using `docker export` and then `docker import` them next run to save some time.

- Travis CI caching - https://docs.travis-ci.com/user/caching/#How-does-the-caching-work%3F
- Circle CI caching - https://circleci.com/docs/how-cache-works/

**Comment by kiview** [comment]
Have you looked into other Nifi images and how they are built?

**Comment by mkobit** [comment]
Other Nifi images that I have seen follow a similar pattern of downloading from a distribution.

- https://github.com/apiri/dockerfile-apache-nifi (apiri is a PMC member on the NiFi/MiNiFi projects)
- https://hub.docker.com/r/aperepel/nifi/~/dockerfile/
- https://github.com/jdye64/docker-nifi/blob/master/docker/Dockerfile

Since mirror urls change, I thought it might make sense to "build from source" so that it could be easier to build new images using newer base versions of Java SDKs.

Could also write some sort of "scrape" that just gets the closest download, but I haven't looked into it.

**Comment by mkobit** [comment]
There are also ways to better handle splitting up each version possibly by branch? It just hasn't been a priority of mine for a while.

**Comment by mkobit** [comment]
https://github.com/docker/docker/issues/32100 will greatly simplify this

**Comment by mkobit** [comment]
Multi-stage builds have made this simpler, but I will not really be supporting this repository moving forward.

It is recommended to use the [official NiFi images](https://hub.docker.com/r/apache/nifi/) and follow up with the Apache NiFi team with any issues.
