### ISSUE TITLE
Where are the images?

### ISSUE THREAD

**Issue by adrianog** [mkobit/docker-nifi#12]
Is this still being maintained?

**Comment by mkobit** [comment]
What are you looking for that you aren't finding? Is something missing from https://hub.docker.com/r/mkobit/nifi/ ?

I am more likely to stop maintaining this soon as this is more formally supported now in the official Apache NiFi repository (see https://hub.docker.com/r/apache/nifi/)

**Comment by adrianog** [comment]
The build status in docker is https://goo.gl/u9XDXt .

**Comment by mkobit** [comment]
Got it, I think I understand.

The build process for this doesn't use Docker Hub (right now).

It uses [Travis CI](https://travis-ci.org/mkobit/docker-nifi) and some Python 3 stuff to generate the Dockerfile, build it, and push it. I did this project as a learning experience for all 3 of those, but now with multi-stage builds I have move this back towards a plain Dockerfile approach.

**Comment by adrianog** [comment]
Thank you make senes.
I'll use the official images if that's what you suggest as well.

I was looking for some experiences on using nifi in a container, there doesn't seem to be much. Hopefully the non-docker guidelines apply to the docker case tout court.

**Comment by adrianog** [comment]
Just as a follow up - I've since discovered https://goo.gl/wNKTWf , useful resource for docker.

Oh! And the awesome nifi github project of course: https://goo.gl/oxGjVD .

**Comment by mkobit** [comment]
Closing this - I have:

-  pushed up 1.4.0 
- added a warning recommending users to use the official NiFi images

Thanks for reaching out!
