### ISSUE TITLE
Investigate switching to Alpine images

### ISSUE THREAD

**Issue by mkobit** [mkobit/docker-nifi#3]
The Java images are very large. NiFi itself weights in at a heavy ~300 MB, too. See if there are some optimizations that can be made to reduce the size of these images.

**Comment by yellowiscool** [comment]
That would be a nice improvement. However, Alpine doesn't use the Glibc by default and that could be a source of issues with precompiled software.

**Comment by mkobit** [comment]
I will not really be supporting this repository moving forward.

It is recommended to use the [official NiFi images](https://hub.docker.com/r/apache/nifi/) and follow up with the Apache NiFi team with any issues.
